01_ZooSite/ZooSite/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ZooSite.Models
{
    public class Customer
    {
        public int CustomerId { get; set; }

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Please enter your first name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Please enter your last name")]
        public string LastName { get; set; }

        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Please enter your email")]
        public string Email { get; set; }

        [Display(Name = "Phone"), DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Please enter your phone")]
        public int PhoneNumber { get; set; }

        [Required(ErrorMessage = "Please enter your adress")]
        public string Address { get; set; }
    }
}

01_ZooSite/ZooSite/Models/Photo.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ZooSite.Models
{
    public class Photo
    {
        public int PhotoID { get; set; }

        [Required]
        public string Title { get; set; }

        [DisplayName("Picture")]
        public string PhotoFileName { get; set; }

        [HiddenInput(DisplayValue = false)]
        public string ImageMimeType { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    }
}

01_ZooSite/ZooSite/Controllers/ZooController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using ZooSite.Data;
using ZooSite.Models;

namespace ZooSite.Controllers
{
    public class ZooController : Controller
    {
        private ZooContext _context;
        private IHostingEnvironment _environment;

        public ZooController(ZooContext context, IHostingEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        public IActionResult Index()
        {
            return View(_context.Photos.ToList());
        }

        public IActionResult VisitorDetails()
        {
            return View();
        }

        [HttpGet]
        public IActionResult BuyTickets()
        {
            return View();
        }

        [HttpPost, ActionName("BuyTickets")]
        public IActionResult BuyTicketsPost(Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Customers.Add(customer);
                _context.SaveChanges();
                return RedirectToAction("ThankYou");
            }
            return View(customer);
        }

        public IActionResult ThankYou()
        {
            return View();
        }

        public IActionResult GetImage(int photoId)
        {
            Photo requestedPhoto = _context.Photos.FirstOrDefault(p => p.PhotoID == photoId);
            if (requestedPhoto != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = "\\images\\";
                string fullPath = webRootpath + folderPath + requestedPhoto.PhotoFileName;

                FileStream fileOnDisk = new FileStream(fullPath, FileMode.Open);
                byte[] fileBytes;
                using (BinaryReader br = new BinaryReader(fileOnDisk))
                {
                    fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                }
                return File(fileBytes, requestedPhoto.ImageMimeType);
            }
            else
            {
                return NotFound();
            }
        }
    }
}

01_ZooSite/ZooSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link type="text/css" rel="stylesheet" href="~/css/zoo-style.css" />
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/js/menubar-functions.js"></script>
    <script src="~/js/slider-functions.js"></script>
</head>
<body>
    <ul class="nav">
        <li><a href="@Url.Action("Index","Zoo")">Attractions</a></li>
        <li><a href="@Url.Action("VisitorDetails","Zoo")">Visitor Info</a></li>
        <li><a href="@Url.Action("BuyTickets","Zoo")">Tickets</a></li>
    </ul>
    <div class="header-container">
        <h1>Welcome to Zoo Center</h1>
        <div class="slider-buttons">
            <img src="~/images/prevArrow.png" class="pre" onclick="prevImage()" />
            <img src="~/images/nextArrow.png" class="pre" onclick="nextImage()" />
        </div>
    </div>
    <div>
        @RenderBody()
    </div>
    @RenderSection("Scripts", false)
</body>
</html>

01_ZooSite/ZooSite/Views/Zoo/BuyTickets.cshtml
@model ZooSite.Models.Customer

@{
    ViewData["Title"] = "BuyTickets";
}

<div class="container buy-tickets">
    <div class="info">
        <div class="step-title">Step 1 - Choose Tickets</div>
        <table class="pricing">
            <tr>
                <td>Adult</td>
                <td id="adultCost">$35</td>
                <td>
                    <select id="adultQuantity">
                        <option selected="selected" value="0">0</option>
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Child</td>
                <td id="childCost">$23</td>
                <td>
                    <select id="childQuantity">
                        <option selected="selected" value="0">0</option>
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Senior</td>
                <td id="seniorCost">$30</td>
                <td>
                    <select id="seniorQuantity">
                        <option selected="selected">0</option>
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select>
                </td>
            </tr>
        </table>
        <div id="summery" class="hidden-div">
            <p>Order Summary</p>
            <table id="totalAmount"></table>
            <label id="sum"></label>
        </div>
    </div>
    <div class="info">
        <div class="step-title">Step 2 - Buy Tickets</div>
        <form method="post" enctype="multipart/form-data" asp-action="BuyTickets">
            <div class="form-field">
                <label asp-for="FirstName"></label>
                <div>
                    <input asp-for="FirstName" />
                    <span asp-validation-for="FirstName"></span>
                </div>
            </div>
            <div class="form-field">
                <label asp-for="LastName"></label>
                <div>
                    <input asp-for="LastName" />
                    <span asp-validation-for="LastName"></span>
                </div>
            </div>
            <div class="form-field">
                <label asp-for="Address"></label>
                <div>
                    <input asp-for="Address" />
                    <span asp-validation-for="Address"></span>
                </div>
            </div>
            <div class="form-field">
                <label asp-for="Email"></label>
                <div>
                    <input asp-for="Email" />
                    <span asp-validation-for="Email"></span>
                </div>
            </div>
            <div class="form-field">
                <label asp-for="PhoneNumber"></label>
                <div>
                    <input asp-for="PhoneNumber" />
                    <span asp-validation-for="PhoneNumber"></span>
                </div>
            </div>
            <div class="form-field" id="formButtons">
                <input class="submit-btn" type="submit" value="Buy" disabled />
                <div id="comment">Please Choose Tickets</div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script src="~/js/form-functions.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

01_ZooSite/ZooSite/Views/Zoo/Index.cshtml
@model IEnumerable<ZooSite.Models.Photo>
@{
    ViewData["Title"] = "Index";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="main-title">Zoo Attractions</h1>

<div class="container">
    @foreach (var item in Model)
    {
        <div class="photo-index-card">
            @if (item.PhotoFileName != null)
            {
                <div class="image-wrapper">
                    <img class="photo-display-img" src="@Url.Action("GetImage", "Zoo", new { PhotoId = item.PhotoID})" />
                </div>
            }
            <h3 class="display-picture-title">@Html.DisplayFor(modelItem => item.Title)</h3>
        </div>
        <div>
            <span class="display">@Html.DisplayFor(model => item.Description)</span>
        </div>
    }
</div>

01_ZooSite/ZooSite/Views/Zoo/ThankYou.cshtml
@{
    ViewData["Title"] = "BuyTicketsPost";
}
<div class="container">
    <h1>Thank You For Your Purchase</h1>
</div>

01_ZooSite/ZooSite/Views/Zoo/VisitorDetails.cshtml
@{
    ViewData["Title"] = "VisitorDetails";
}

<div class="container">
    <div class="info">
        <p class="contact-title">Park Hours</p>
        <p class="sub-header">Weekends and Holidays</p>
        <p>10:00 AM - 5:00 PM</p>
        <p>Monday - Friday</p>
        <p>10:00 AM - 5:30 PM</p>
    </div>
    <div class="info">
        <p class="contact-title">Zoo Schedule</p>
        <table>
            <tr>
                <td>09:00 AM</td>
                <td>Zoo Opens</td>
            </tr>
            <tr>
                <td>11:00 AM</td>
                <td>Sea Water Show</td>
            </tr>
            <tr>
                <td>2:00 PM</td>
                <td>Sea Lion Feeding</td>
            </tr>
            <tr>
                <td>5:00 PM</td>
                <td>Exhibits Close</td>
            </tr>
            <tr>
                <td>5:30 PM</td>
                <td>Zoo Closes</td>
            </tr>
        </table>
    </div>
</div>